INSERT INTO t_tag(tag_name, tag_type)
VALUES ('bad-quality', 'QUALITY'),
       ('good-quality', 'QUALITY'),
       ('case','BINDING'),
       ('perfect','BINDING'),
       ('comb','BINDING'),
       ('spiral','BINDING'),
       ('thermal','BINDING'),
       ('saddle-stitch','BINDING'),
       ('detective','GENRE'),
       ('adventure','GENRE'),
       ('action','GENRE'),
       ('comic','GENRE'),
       ('mystery','GENRE'),
       ('history','GENRE'),
       ('horror','GENRE'),
       ('romance','GENRE'),
       ('science-fiction','GENRE'),
       ('thriller','GENRE'),
       ('biography','GENRE'),
       ('poetry','GENRE'),
       ('memoir','GENRE'),
       ('guide','GENRE'),
       ('english','LANGUAGE'),
       ('romanian','LANGUAGE'),
       ('russian','LANGUAGE'),
       ('french','LANGUAGE'),
       ('german','LANGUAGE'),
       ('spanish','LANGUAGE')
ON CONFLICT DO NOTHING;
